name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
      
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files_ignore_separator: " "
       
    - name: Write File
      run: echo ${{ steps.changed-files.outputs.all_changed_files }} > pathes.txt && less ./pathes.txt && realpath pathes.txt
      shell: bash
      
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
      # Установка зависимостей pip
    - name: Python Dependency Installation
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: restore_env_cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
    #запуск скрипта
    - run: pip install -r requirements.txt
      shell: bash
    - name: Run a Python script
      run: python ProjectProgram.py
      shell: bash
#     - name: Send mail
#       uses: dawidd6/action-send-mail@v3.6.1
#       with:
#         server_address: smtp.mail.ru
#         server_port: 465
#         username: secret_detection@mail.ru
#         password: tAraIKAit11&
#         subject: secreti suda
#         to: this-is-yashka@yandex.ru
#         from: Slavchik Luchshiy
#         body: >
#           Salyami snowballs 
