name: 'Det_sec'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
  logmail_address:  # id of input
    description: 'address of mail for logging (optional)'
    required: false
    default: ''
  logmail_password:  # id of input
    description: 'password of mail for logging (optional)'
    required: false
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
      
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files_ignore_separator: " "
      
    - name: Write File
      run: echo ${{ steps.changed-files.outputs.all_changed_files }} > pathes.txt && less ./pathes.txt && realpath pathes.txt
      shell: bash
      
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
      # Установка зависимостей pip
    - name: Python Dependency Installation
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: restore_env_cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
    #запуск скрипта
    - run: pip install -r requirements.txt
      shell: bash
    - name: Run a Python script
      run: python ProjectProgram.py
      shell: bash
      
     #если есть секреты, вываливаемся в ошибку
    - name: Send mail
      if: $(grep '1' Program_predictions.txt)
      uses: dawidd6/action-send-mail@v3.6.1
      with:
        server_address: smtp.mail.ru
        server_port: 465
        username: det_sec tool of ${{ github.repository }} repository
        password: ${{ inputs.logmail_password }}
        subject: ${{ github.job }} job
        to: ${{ inputs.logmail_address }}}}
        from: github angular workflow
        body: >
           A person with nick "$GITHUB_ACTOR" in repository ${{ github.workflow }} 
           of ${{ github.repository }}, branch "$GITHUB_BASE_REF" has probably posted a secret. 
           Commit SHA: $GITHUB_SHA
           The process took
           seconds.
      
      
    - name: if there any secrets
      run: if grep '1' Program_predictions.txt; then exit 1; fi
      shell: bash     
     
     
