on: [push]

env:
  main-content: ''

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    name: secret scanning
    steps:
    
      - uses: actions/checkout@v3
      
      - id: secret_scanning
        uses: mihakremen/det_sec@reverse_models

      - name: list-found-secrets
        if: failure()
        run: |
             echo "main-content=$(echo ${{ steps.secret_scanning.outputs.found-secrets }})" >> GITHUB_ENV
             

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.mail.ru
          server_port: 465
          username: ${{ secrets.LOGMAIL_ADDRESS }}
          password: ${{ secrets.LOGMAIL_PASSWORD }}
          subject: ${{ github.job }} job
          to: ${{ secrets.LOGMAIL_ADDRESS }}
          from: det_sec tool
          body: |
           Attention! ${{ github.workflow }} process was failed.
           A person with nickname ${{ github.actor }} in repository ${{ github.repository }} has probably posted a secret.
           Branch ${{ github.ref }}  
           Commit SHA: ${{ github.sha }}
           Main content: 
           ${{ env.found-secrets }}
