on:
  label:
    types: [created, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: secret scanning
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: mihakremen/det_sec@main
        with:
          logmail_address: ${{ secrets.LOGMAIL_ADDRESS }}
          logmail_password: ${{ secrets.LOGMAIL_PASSWORD }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
