on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: secret scanning
    steps:
    
      - uses: actions/checkout@v3
      
      - id: secret_scanning
        uses: mihakremen/det_sec@main
        with:
          logmail_address: ${{ secrets.LOGMAIL_ADDRESS }}
          logmail_password: ${{ secrets.LOGMAIL_PASSWORD }}
          
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
        

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.mail.ru
          server_port: 465
          username: ${{ secrets.LOGMAIL_ADDRESS }}
          password: ${{ secrets.LOGMAIL_PASSWORD }}
          subject: ${{ github.job }} job
          to: ${{ secrets.LOGMAIL_ADDRESS }}
          from: github angular workflow
          body: >
           A person with nick ${{ github.actor }} in repository ${{ github.repository }}, 
           running ${{ github.workflow }} process, branch ${{ github.ref }} has probably posted a secret. 
           Commit SHA: ${{ github.sha }}
