on: [push]

env:
  main-content: ''

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    name: secret scanning
    steps:
    
      - uses: actions/checkout@v3
      
      - id: secret_scanning
        uses: mihakremen/det_sec@main

      - name: list-found-secrets
        if: failure()
        run: |
             echo "main-content=$(echo ${{ steps.secret_scanning.outputs.found-secrets }})" >> GITHUB_ENV
             

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.mail.ru
          server_port: 465
          username: ${{ secrets.LOGMAIL_ADDRESS }}
          password: ${{ secrets.LOGMAIL_PASSWORD }}
          subject: ${{ github.job }} job
          to: ${{ secrets.LOGMAIL_ADDRESS }}
          from: github angular workflow
          body: >
           Attention! ${{ github.workflow }} process was failed. $'/n'
           A person with nick ${{ github.actor }} in repository ${{ github.repository }}, 
            , branch ${{ github.ref }} has probably posted a secret. 
           Commit SHA: ${{ github.sha }}
           Main content: ${{ env.found-secrets }}


# $mail->SMTPSecure='ssl';
# $mail->Host=""smtp.gmail.com"";
# //$mail->Host=""smtp.hostinger.in"";
# $mail->Port='465';
# $mail->isHTML();
# $mail->Username=<EMAIL>;
# $mail->Password='Alexis0';
# $mail->SetFrom(<EMAIL>);
# $mail->AddReplyTo($email);
# $mail->FromName=$first_name."" "".$last_name;
# $mail->Subject=""New Message from digiOmega Contact Form"";
# $email_content = ""Name: $first_name + $last_name <br>"";
# $email_content .= ""Phone: $phone <br>"";",1,php
